project:
  type: website

website:
  title: "Data Woman"
  site-url: https://datawoman.com
  navbar:
    toggle-position: right
    background: "#f0eeeb"
    left:
      - text: "Data for Science"
        menu: 
        - text: "Data as a goal"
          href: pages/data-as-goal.qmd
        - text: "Science AI in 2025"
          href: pages/ether0.qmd
        - text: "Data for machine learning"
          href: pages/hugging-face.qmd
        - text: "Science AI in 2023"
          href: pages/ai-earlyeve.qmd
        - text: "It's the data, stupid"
          href: pages/the-data-stupid.qmd
      - text: "Making Orgs Work"
        menu: 
        - text: "Starting up data science"
          href: pages/posit-keynote.qmd
        - text: "What metrics are for"
          href: pages/metrics-reality.qmd
        - text: "Organizational innovation"
          href: pages/fros.qmd
        - text: "Agile for data science"
          href: pages/agile-for-ds.qmd
        - text: "The pain of DS in orgs"
          href: pages/pain-of-ds.qmd
      - text: "Tech Tools"
        menu: 
        - text: "Serverless data apps"
          href: pages/serverless-apps.qmd
        - text: "Why vibe coding"
          href: pages/vibe-coding.qmd
        - text: "Chatbots"
          href: pages/methods-chatbot.qmd
        - text: "Simulation as a tool"
          href: pages/simulation.qmd
      - text: "Women in Leadership"
        menu: 
        - text: "Lady Gaga"
          href: pages/lady-gaga.qmd
        - text: "Jacinda Arden"
          href: pages/jacinda.qmd
        - text: "Jane Goodall"
          href: pages/jane-goodall.qmd
        - text: "The loneliness of onlyness"
          href: pages/onlyness.qmd
        - text: "Asterisks"
          href: pages/asterisks.qmd
        - text: "Agile at home"
          href: pages/schario.qmd
      - text: "The nature of AI"
        menu: 
        - text: "The bitter lesson"
          href: pages/bitter-lesson.qmd
        - text: "Reinforcement learning"
          href: pages/reinforcement-learning.qmd
        - text: "What is an AI model, really?"
          href: pages/how-llms-work.qmd
  
  page-navigation: true

  back-to-top-navigation: false

format:
  html:
    theme: [lux, custom.scss]
    css: styles.css
    toc: true
    grid:
      sidebar-width: 0px
      body-width: 1000px
      margin-width: 0px

execute: 
  freeze: auto