[build]
  publish = "_site"
  command = """
    cd /tmp && \
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.57/quarto-1.5.57-linux-amd64.tar.gz && \
    tar -xzf quarto-1.5.57-linux-amd64.tar.gz && \
    cd /opt/build/repo && \
    /tmp/quarto-1.5.57/bin/quarto render
  """