[build]
  publish = "_site"
  command = """
    curl -LO https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.57/quarto-1.5.57-linux-amd64.tar.gz && \
    tar -xzf quarto-1.5.57-linux-amd64.tar.gz && \
    export PATH=$PATH:$(pwd)/quarto-1.5.57/bin && \
    quarto render
  """