[build]
  publish = "_site"
  command = """
    wget https://github.com/quarto-dev/quarto-cli/releases/download/v1.5.57/quarto-1.5.57-linux-amd64.tar.gz && \
    mkdir -p /opt/quarto && \
    tar -C /opt/quarto -xzf quarto-1.5.57-linux-amd64.tar.gz && \
    /opt/quarto/quarto-1.5.57/bin/quarto render
  """