---
title: All Time Top 5 rstudio::conf Talks
author: Elaine McVey
date: '2020-02-17'
slug: top-5-rstudio-conf-talks-of-all-time
categories: []
tags: []
keywords:
  - tech
---

```{r, echo=FALSE}
library(emo)
```


rstudio::conf is my very favorite conference. It's welcoming and full of great people to connect with. (And the hex stickers are epic!) The quality of the presentations is excellent, and in addition to the ones I attend, I look forward to the videos being posted so I can watch ones I couldn't get to. 

From all these great talks, a few have really stuck with me and impacted my thinking over time. These are Big Idea talks, or at least the big ideas are what I remember from them. They should be interesting even if to non-R-users. 

So, based on the standard "talks I keep thinking about", I present my **All Time Top 5 rstudio::conf talks**. I've given them some new titles to emphasize the point that stuck with me.

## Don't Be Jerks (and how we teach programming)
#### Felienne, rstudio::conf 2019, [Explicit Direct Instruction in Programming Education](https://resources.rstudio.com/rstudio-conf-2019/opening-keynote-day2) 

This was a keynote that had nothing to do with R, and yet highlighted for me the strengths of the R community. Anyone who works as a developer or teaches programming should watch this talk! Bonus, Felienne's hand drawn slides are unique and fun.

Felienne tells the story of her computer science PhD research, which was to develop a domain-specific language for finance. She observed that finance already has such a language - it's Excel. In making the case that spreadsheets are programming, she repeatedly got pushback from the professional community that "it's not real programming". She observes that other communities she's part of, like runners and knitters, do not have this critical and unwelcoming "you're doing it wrong" response that seems common in the programming community. 

As she goes on to teach programming to kids on weekends, she reflects on how we learn and teach programming. Because 80% of programmers are self-taught, "We don't know how to teach programming. We don't have a shared, collective memory of what a programming lesson looks like, and that does something to us as a community." She connects the way books about programming for kids present it as something you have to figure out through trial and error to a particular education philosophy - constructivism. She cites research that has concluding that this is _not_ the winning approach, and kids learn much more from an emphasis on explanation and practice. "You don't become an export by doing expert things. People think motivation leads to skill, but actually skill leads to motivation." She concludes with some specific approaches to teaching programming that are proving successful.

## Falling into the Pit of Success
#### Hadley Wickham, rstudio::conf 2017, [Data Science in the Tidyverse](https://resources.rstudio.com/rstudio-conf-2017/data-science-in-the-tidyverse-hadley-wickham)

## Some of My Best Friends Use Spreadsheets
#### Jenny Bryan, useR! 2016, [jailbreakr: Get out of Excel, free](https://channel9.msdn.com/events/useR-international-R-User-conference/useR2016/jailbreakr-Get-out-of-Excel-free?term=jenny%20bryan&lang-en=true) 

_I realized as I was looking up the video links for this post that this talk was not actually given at rstudio::conf `r emo::ji("flushed")`. It pre-dates the first rstudio::conf and is actually from useR! 2016 (also a great conference!). But since it's stuck with me for that long, I'm keeping it as an honorary member of this list._

What stuck with me about this one is the *importance of user empathy*. In this case, users are people who use spreadsheets. Accepting that many, many smart people use spreadsheets for data analysis and asking why led to some key insight. Jenny observed that spreadsheets provide a lot of immediate utility for their users, by combining tools to manage data, logic, visualization, formatted tables -- all with reactivity thrown in! A spreadsheet effectively collects all these pieces into a single location that can be easily shared. I had never thought about spreadsheets this way, but it totally makes sense. This was an early step for me in shifting from thinking less about why my tools are better to thinking more about the perspectives of users, and how I can build things that meet them where they are. (And fortunately Jenny has created several packages that make extracting data from spreadsheets less painful for R users!)

## The Nature of Corporations (and why you should care)
#### J.J. Allaire, userR! 2020, [Open Source Software for Data Science](https://resources.rstudio.com/rstudio-conf-2020/rstudio-open-source-software-for-data-science-j-j-allaire)

## The Future of Data Science (and why we will still matter)
#### Eduardo Ariño de la Rubia, userR! 2020, [Value in Data Science Beyond Models in Production](https://resources.rstudio.com/rstudio-conf-2020/value-in-data-science-beyond-models-in-production-eduardo-arino-de-la-rubia)





